#ifndef MYOS_H_
#define MYOS_H_

#define MYOS_VERSION_MAJOR 0
#define MYOS_VERSION_MINOR 0
#define MYOS_VERSION_PATCH 1

#ifdef MYOS_TAG
#define MYOS_VERSION STRINGIFY_(MYOS_TAG)
#else
#define MYOS_VERSION STRINGIFY_(MYOS_VERSION_MAJOR) "." STRINGIFY_(MYOS_VERSION_MINOR) "." STRINGIFY_(MYOS_VERSION_PATCH)
#endif

#define STRINGIFY_HELPER_(name, ...) #name
#define STRINGIFY_(...) STRINGIFY_HELPER_(__VA_ARGS__, )

#endif/*MYOS_H_*/
